### PR TITLE
Lock down APIM inbound traffic to Front Door only

### PR DESCRIPTION
**Pull request by CarloGarcia**
Would it not make the solution more secure to lock down the NSG to only accept traffic from Front Door only? Since the NSG allows traffic from the "Internet" service tag, callers could potentially access the API directly (and bypass Front Door) if they discovered the URL/IP right?

In the change above I am proposing we replace the service tag with "AzureFrontDoor.Backend".

### CODE REVIEW

**Comment by paolosalvatori** [comment]
Yes, I considered this option and I also tried it before publishing the article. I decided not to include this option in the ARM template because if you create an inbound rule for the NSG associated with the subnet hosting APIM, you lose the ability to use the developer portal, or at least, you should access the developer portal through Front Door. You also lose the ability to use the Azure Portal to test APIs. I'm looking into this with the Front Door and APIM team. I

When API Management is deployed in a virtual network and configured to use the external access type as explained at How to use Azure API Management with virtual networks, the API Gateway and developer portal are accessible from the public internet via an external load balancer and the gateway can access resources within the virtual network. If you want to force client applications to invoke the API Gateway through Azure Front Door, you can proceed as follows:
•	You can set one or more inbound rules in the NSG associated with the subnet hosting APIM to accept inbound traffic on HTTP/HTTPS ports only from Front Door using the AzureFrontDoor.Backend service tag. This way the public endpoints exposed by APIM, the API Gateway, and Developer portal, will accept calls only via Azure Front Door. Refer AzureFrontDoor.Backend section in Azure IP Ranges and Service Tags for Front Door's IPv4 backend IP address range or you can also use the service tag AzureFrontDoor.Backend in your network security groups or with Azure Firewall.
•	If you want to provide access to the developer portal to users, you can create an additional inbound rule to provide access to the range of IP addresses used by users, or you can deploy the self-hosted developer portal wherever you like, on-premises or in the cloud (e.g. a VM on Azure), and create an inbound rule in the NSG associated to the subnet hosting APIM to accept inbound traffic on HTTP/HTTPS ports to allow traffic from the public IP of the physical or virtual machine hosting the self-hosted developer portal. 

Let me know if this answers your question!

**Comment by paolosalvatori** [comment]
Hi @CarloGarcia, I double-checked with the API Management team and at the end, I decided to add a boolean parameter called allowTrafficOnlyFromFrontDoor that specifies whether the inbound traffic on ports 80 (HTTP) and 443 (HTTPS) is allowed only from Azure Front Door, and I documented the side effects of allowing ingress traffic only from Front Door. I close this PR as it is included in the new implementation. Thanks for the feedback :)

**Comment by catapopa247** [comment]
This NSG lock-down approach only works if the APIM is on Developer or Premium SKU (thus being included in a VNET).
If your APIM is on Standard and it isn't part of a VNET, basically you never lockdown connections on APIM to only accept front FrontDoor, because the NSG is applied only on traffic that eventually passes the VNET.
Having the APIM on Standard, the trafic from FrontDoor to APIM will go via Internet. 

If you want to have a general way on how to control traffic on APIM to only come front FrontDoor, then I recommend you to do a filtering at APIM level and accept only requests that come specifically from FrontDoor.

**Comment by paolosalvatori** [comment]
Hi @catapopa247 the sample was intended to be used under the following conditions:

- APIM is injected in virtual network
- APIM SKU is Developer or Premium

in other words, the sample does not cover other scenarios.

**Pull request closed without merging**
